# Generated by Django 5.0.2 on 2024-08-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tcg', models.CharField(choices=[('magic_the_gathering', 'MAGIC'), ('one_piece', 'ONE_PIECE')], max_length=50)),
                ('deck_type', models.CharField(choices=[('commander', 'COMMANDER'), ('standard', 'STANDARD'), ('modern', 'MODERN'), ('pioneer', 'PIONEER')], max_length=50, null=True)),
                ('colors', models.CharField(choices=[('White', 'W'), ('Blue', 'U'), ('Black', 'B'), ('Red', 'R'), ('Green', 'G'), ('Colorless', 'C')], default='Colorless', max_length=50)),
                ('photo', models.URLField(blank=True, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cmc', models.IntegerField(default=0)),
                ('mana_cost', models.CharField(max_length=50)),
                ('colors', models.CharField(choices=[('White', 'W'), ('Blue', 'U'), ('Black', 'B'), ('Red', 'R'), ('Green', 'G'), ('Colorless', 'C')], default='Colorless', max_length=50)),
                ('type_line', models.CharField(max_length=255)),
                ('rarity', models.CharField(max_length=50)),
                ('cmdr_legal', models.CharField(max_length=50)),
                ('img', models.URLField()),
                ('purchase_uris', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.deck')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.user'),
        ),
    ]
