# Generated by Django 5.0.2 on 2024-08-07 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_leader',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='colors',
            field=models.CharField(choices=[('White', 'W'), ('Blue', 'U'), ('Black', 'B'), ('Red', 'R'), ('Green', 'G'), ('Colorless', 'C')], default='Colorless', max_length=50, null=True),
        ),
    ]
