# Generated by Django 5.0.2 on 2024-08-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_remove_card_deck_deck_deck_leader_alter_deck_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
