# Generated by Django 5.0.2 on 2024-08-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_card_colors_alter_deck_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deck_leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.card'),
        ),
    ]
